### PR TITLE
use better random to generate seed with full range

### PR DESCRIPTION
**Pull request by Entroper**

### CODE REVIEW

**Comment by nic0lette** [comment]
> Lgtm does ToHex left pad with zeroes?

`ValidateSeed` does that, actually. :) (I added that awhile ago because I was annoyed at having to add leading zeros XD)

**Comment by Entroper** [comment]
ToHex() pads anyway.  Should this go to `dev` or `alpha`?

**Comment by nic0lette** [comment]
alpha and cherry pick over would be my suggestion, but whatever you think is best. :)

**Comment by Steven-Biro** [comment]
@Entroper should this be closed now?

**Comment by Entroper** [comment]
I tried to rebase this and it was too messed up because the indentation changed for the entire @functions section.  Closing this and re-doing from scratch.

**Pull request closed without merging**
