### PR TITLE
Add some new fun% enemy names

### PR DESCRIPTION
**Pull request by tetron**
WzOgre →Grover (from Sesame Street)
WzVAMP → Edward (from Twilight)
R.GOYLE →ARGYLE (sounds similar)
R.Ankylo →FunPolic (from DW1R)
WzMUMMY →MOMMY (someone has to be in charge)
BADMAN →Batman (I always think this when I see them)
EVILMAN →OKAYMAN (name moved over)

Whether to capitalize names or not is confusing

### CODE REVIEW

**Comment by DocRosalia** [comment]
Kary -> Kelly (joke from when I accidentally said Kelly instead of Kary)
WizOgre -> DIRGE (wizogres are usually in formations with cerebuses)

**Comment by tetron** [comment]
I don't think WzOgres run with cereberus, it's the blue one that's weaker, hyena maybe?

I like "Grover" for WzOgre because they are both blue.

I should definitely add Kary -> Kelly.

**Comment by tetron** [comment]
I have been schooled

**Review by wildham0 — APPROVED** [review]

**Pull request merged**
